apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: rethinkdb
  name: rethinkdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb
    spec:
      containers:
      - image: rethinkdb
        name: rethinkdb
