apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: rethinkdb
  name: rethinkdb
spec:
  ports:
  - name: admin
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: client
    port: 28015
    protocol: TCP
    targetPort: 28015
  - name: intracluster
    port: 29015
    protocol: TCP
    targetPort: 29015
  selector:
    app: rethinkdb
  type: ClusterIP
